# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 12:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('album_id', models.IntegerField(primary_key=True, serialize=False)),
                ('pic_url', models.CharField(max_length=1024)),
                ('publish_time', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('artist_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('alias', models.CharField(default='', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('song_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('popularity', models.FloatField()),
                ('clicked_num', models.IntegerField(default=0)),
                ('listened_num', models.IntegerField(default=0)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicsearch.Album')),
                ('artists', models.ManyToManyField(to='musicsearch.Artist')),
            ],
        ),
    ]
