# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 15:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicsearch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='name',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='musicsearch.Album'),
        ),
        migrations.AlterField(
            model_name='song',
            name='artists',
            field=models.ManyToManyField(blank=True, null=True, to='musicsearch.Artist'),
        ),
    ]
