# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicsearch', '0002_auto_20170524_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='pic_url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
